# Generated by Django 4.2.3 on 2023-07-04 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Navbar',
            new_name='Link',
        ),
    ]
